USE TestDB;
GO
CREATE TABLE GroupTypes(
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL
);
GO
CREATE TABLE Groups(
	Id INT IDENTITY PRIMARY KEY, 
	Name NVARCHAR(50) UNIQUE NOT NULL,
	Description NVARCHAR(255) NOT NULL ,
	GroupTypeId INT NOT NULL FOREIGN KEY(GroupTypeId) REFERENCES GroupTypes(Id),
	CreatedDate DATETIME NOT NULL
);
GO
CREATE TABLE GroupUsers(
	Id INT IDENTITY PRIMARY KEY, 
	PhoneNumber VARCHAR(20) NOT NULL,
	GroupId INT NOT NULL FOREIGN KEY(GroupId) REFERENCES Groups(Id)
);
GO